### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by nballen-tx** [iSarabjitDhiman/TweeterPy#12]
Hi,

Looks like the rate limit argument is not working any more?

twitter = TweeterPy()
twitter.load_session(session_file_path=path)
twitter.get_user_id('',return_rate_limit=True)

TypeError: get_user_id() got an unexpected keyword argument 'return_rate_limit'

twitter.get_friends('',follower=True,return_rate_limit=True)
get_friends() got an unexpected keyword argument 'return_rate_limit'

Looking for get_user_tweets rate limit too.

Thanks,

**Comment by iSarabjitDhiman** [comment]
Duplicate : #11
