### ISSUE TITLE
Login does not work any more

### ISSUE THREAD

**Issue by nballen-tx** [iSarabjitDhiman/TweeterPy#17]
Hi,

Looks like the login gateway has changed or blocked somehow.

```python
twitter = TweeterPy()
twitter.login(account,password)

API Updated Successfully.
'content-type'3

File /opt/conda/lib/python3.9/site-packages/tweeterpy/login_util.py:33, in TaskHandler._get_flow_token(self)
     22 params = {'flow_name': 'login'}
     23 payload = {'input_flow_data': {
     24     'flow_context': {'debug_overrides': {}, 'start_location': {'location': 'manual_link'}, }, },
     25     'subtask_versions': {'action_list': 2, 'alert_dialog': 1, 'app_download_cta': 1, 'check_logged_in_account': 1,
   (...)
     31                          'settings_list': 7, 'show_code': 1, 'sign_up': 2, 'sign_up_review': 4, 'tweet_selection_urt': 1, 'update_users': 1,
     32                          'upload_media': 1, 'user_recommendations_list': 4, 'user_recommendations_urt': 1, 'wait_spinner': 3, 'web_modal': 1}}
---> 33 return make_request(Path.TASK_URL, method="POST", params=params, json=payload)

File /opt/conda/lib/python3.9/site-packages/tweeterpy/request_util.py:38, in make_request(url, session, method, max_retries, timeout, **kwargs)
     35 if api_limit_stats.get('rate_limit_exhausted'):
     36     print(
     37         f"\033[91m Rate Limit Exceeded:\033[0m {api_limit_stats}")
---> 38 raise error

File /opt/conda/lib/python3.9/site-packages/tweeterpy/request_util.py:22, in make_request(url, session, method, max_retries, timeout, **kwargs)
     20 api_limit_stats = util.check_api_rate_limits(response)
     21 soup = bs4.BeautifulSoup(response.content, "lxml")
---> 22 if "json" in response.headers["Content-Type"]:
     23     return util.check_for_errors(response.json())
     24 response_text = "\n".join(
     25     [line.strip() for line in soup.text.split("\n") if line.strip()])

File /opt/conda/lib/python3.9/site-packages/requests/structures.py:52, in CaseInsensitiveDict.__getitem__(self, key)
     51 def __getitem__(self, key):
---> 52     return self._store[key.lower()][1]

KeyError: 'content-type'
```

Thanks,

**Comment by iSarabjitDhiman** [comment]
It seems to be working fine on my side. Do you mind giving it another try? Let me know if the issue persists.

**Comment by nballen-tx** [comment]
Just tried it, still the same error.

**Comment by nballen-tx** [comment]
`File /opt/conda/lib/python3.9/site-packages/tweeterpy/tweeterpy.py:189, in TweeterPy.login(self, username, password)
    187 if password is None:
    188     password = getpass.getpass()
--> 189 TaskHandler().login(username, password)
    190 util.generate_headers(session=self.session)

File /opt/conda/lib/python3.9/site-packages/tweeterpy/login_util.py:93, in TaskHandler.login(self, username, password)
     91 otp = None
     92 task_flow_mapper = self._create_task_mapper(username,password,otp)
---> 93 response = self._get_flow_token()
     94 self._get_javscript_instrumentation_subtask()
     95 while tasks_pending:

File /opt/conda/lib/python3.9/site-packages/tweeterpy/login_util.py:33, in TaskHandler._get_flow_token(self)
     22 params = {'flow_name': 'login'}
     23 payload = {'input_flow_data': {
     24     'flow_context': {'debug_overrides': {}, 'start_location': {'location': 'manual_link'}, }, },
     25     'subtask_versions': {'action_list': 2, 'alert_dialog': 1, 'app_download_cta': 1, 'check_logged_in_account': 1,
   (...)
     31                          'settings_list': 7, 'show_code': 1, 'sign_up': 2, 'sign_up_review': 4, 'tweet_selection_urt': 1, 'update_users': 1,
     32                          'upload_media': 1, 'user_recommendations_list': 4, 'user_recommendations_urt': 1, 'wait_spinner': 3, 'web_modal': 1}}
---> 33 return make_request(Path.TASK_URL, method="POST", params=params, json=payload)

File /opt/conda/lib/python3.9/site-packages/tweeterpy/request_util.py:38, in make_request(url, session, method, max_retries, timeout, **kwargs)
     35 if api_limit_stats.get('rate_limit_exhausted'):
     36     print(
     37         f"\033[91m Rate Limit Exceeded:\033[0m {api_limit_stats}")
---> 38 raise error

File /opt/conda/lib/python3.9/site-packages/tweeterpy/request_util.py:22, in make_request(url, session, method, max_retries, timeout, **kwargs)
     20 api_limit_stats = util.check_api_rate_limits(response)
     21 soup = bs4.BeautifulSoup(response.content, "lxml")
---> 22 if "json" in response.headers["Content-Type"]:
     23     return util.check_for_errors(response.json())
     24 response_text = "\n".join(
     25     [line.strip() for line in soup.text.split("\n") if line.strip()])

File /opt/conda/lib/python3.9/site-packages/requests/structures.py:52, in CaseInsensitiveDict.__getitem__(self, key)
     51 def __getitem__(self, key):
---> 52     return self._store[key.lower()][1]

KeyError: 'content-type'`

**Comment by iSarabjitDhiman** [comment]
I still can't replicate the issue. Here is what you can do.

Go to login_util.py file. 

(Scroll down to the very bottom) Go to line 149 in where it raises the error in validate_response function.

```python
"""
just print the response before throwing an error and see if it helps. 
"""
print(response)
raise error
```

**Comment by iSarabjitDhiman** [comment]
You are right, content-type is not in response header which is strange. Btw what do you get in response? NoneType, some html or json object? 
print(response.headers) returns response headers (headers sent by the server(twitter).)
Instead of printing response.headers, try printing the response itself, check what type of response do you get.

**Comment by nballen-tx** [comment]
Tried to print print(response.content)

```python
b''
b''ry No. ==> 1
b''ry No. ==> 2
'content-type'3
```

Look it is empty in reponse.

Above are from the master branch, and I tried other accounts and the results are the same.

**Comment by nballen-tx** [comment]
async-await branch is actually fine though.

what has been changed regarding the login machnism?

**Comment by iSarabjitDhiman** [comment]
Try this out.
 https://github.com/iSarabjitDhiman/TweeterPy/issues/2#issuecomment-1621880787

pip install Brotli

Recently a similar issue was opened, we were getting an empty response. We managed to fix it by installing the Brotli library. Let me know if it still doesn't get fixed, I will try to replicate the issue on my end in the meantime.

**Comment by nballen-tx** [comment]
my original install is below, FYI

pip install tweeterpy --no-dependencies
