### ISSUE TITLE
Master Branch responsive_web_media_download_video_enabled

### ISSUE THREAD

**Issue by nballen-tx** [iSarabjitDhiman/TweeterPy#19]
It was working fine last week and now it returns

````python
twitter.get_user_tweets('elonmusk', total=10)
````

````python
The following features cannot be null: responsive_web_media_download_video_enabled
{'data': [], 'cursor_endpoint': None, 'has_next_page': True}
````

Do you happen to know what is missing here?

**Comment by iSarabjitDhiman** [comment]
> It was working fine last week and now it returns
> 
> ````python
> twitter.get_user_tweets('elonmusk', total=10)
> ````
> 
> ````python
> The following features cannot be null: responsive_web_media_download_video_enabled
> {'data': [], 'cursor_endpoint': None, 'has_next_page': True}
> ````
> 
> Do you happen to know what is missing here?

Yeah its the features list, I have to update it again. Elon is keep making these changes. I gotta find some way to dynamically update the features list/changes on its own, like api updater.

**Comment by nballen-tx** [comment]
Thanks - waiting for you code update.

Will you update both master and async?

**Comment by iSarabjitDhiman** [comment]
> Thanks - waiting for you code update.
> 
> Will you update both master and async?

Yes I will both. Also give me an update on the event loop thing. You have to set config.USING_EVENT_LOOP to True. Let me know if its working.

**Comment by codilau** [comment]
I can confirm that even though no error occurs anymore, like the one OP mentioned, the tweet list still returns empty

**Comment by iSarabjitDhiman** [comment]
> I can confirm that even though no error occurs anymore, like the one OP mentioned, the data list still returns empty

hey @codilau could u please give it another shot, may be in a virtual environment. I just checked it on my side, its working for me. Try reinstalling it. Let me know if the issue persists.
