### ISSUE TITLE
can't get twitter list from search method

### ISSUE THREAD

**Issue by freedom-wy** [iSarabjitDhiman/TweeterPy#2]
i use tweeterpy request twitter search

```
from tweeterpy import TweeterPy
from tweeterpy import config

config.PROXY = {"http": "127.0.0.1:7891", "https": "127.0.0.1:7891"}
config.TIMEOUT = 10

twitter = TweeterPy()
data = twitter.search(search_query="hello world")
print(data)
```

response is none list

```
'content-type'

'content-type'
{'data': [], 'cursor_endpoint': None, 'has_next_page': True}
```

**Comment by iSarabjitDhiman** [comment]
Twitter recently put restrictions on the guest sessions, meaning you can't fetch data without log Ins anymore. If you try to open twitter without login, they will redirect you to the login. So you gonna have to use a logged in (authenticated) session before you start using TweeterPy. Check [Login feature](https://github.com/iSarabjitDhiman/TweeterPy/blob/c246cacff76a281ca3f0a77ab16180ce26745b0b/docs/docs.md?plain=1#L28) to use a logged in session. Also, make sure you are using the actual proxies OR you can comment the proxy code if you don't want to use any proxies.

**Comment by freedom-wy** [comment]
```
from tweeterpy import TweeterPy

from tweeterpy import config

config.PROXY = {"http": "127.0.0.1:7891", "https": "127.0.0.1:7891"}

twitter = TweeterPy()
twitter.login("XXXX", "XXXX")
twitter.save_session()  # Save session if you don't want to login everytime you use the tool again.
data = twitter.search(search_query="hello world", total=50)
print(data)
```

response 

```
API Updated Successfully.
Successfully Logged In..
Expecting value: line 1 column 2 (char 1)
Expecting value: line 1 column 2 (char 1)
{'data': [], 'cursor_endpoint': None, 'has_next_page': True}
```

**Comment by iSarabjitDhiman** [comment]
> ```
> from tweeterpy import TweeterPy
> 
> from tweeterpy import config
> 
> config.PROXY = {"http": "127.0.0.1:7891", "https": "127.0.0.1:7891"}
> 
> twitter = TweeterPy()
> twitter.login("XXXX", "XXXX")
> twitter.save_session()  # Save session if you don't want to login everytime you use the tool again.
> data = twitter.search(search_query="hello world", total=50)
> print(data)
> ```
> 
> response
> 
> ```
> API Updated Successfully.
> Successfully Logged In..
> Expecting value: line 1 column 2 (char 1)
> Expecting value: line 1 column 2 (char 1)
> {'data': [], 'cursor_endpoint': None, 'has_next_page': True}
> ```

That's weird. Its working just fine on my end. Have you tried using it without the proxy as I showed above? If it works without the proxy then its your proxy. Also let me know what type of proxies are you using( datacenter, residentails)? If it still doesn't work, let me know , I will look into it.
