### ISSUE TITLE
Error on login with auth_token

### ISSUE THREAD

**Issue by codilau** [iSarabjitDhiman/TweeterPy#23]
Might be related to the issue solved in your last commit

API Updated Successfully.
Could not login account with auth_token, Twitter returned {'message': 'The following features cannot be null: creator_subscriptions_tweet_preview_api_enabled', 'extensions': {'name': 'BadRequestError', 'source': 'Client', 'code': 336, 'kind': 'Validation', 'tracing': {'trace_id': '5e01127c0bb131c2'}}, 'code': 336, 'kind': 'Validation', 'name': 'BadRequestError', 'source': 'Client', 'tracing': {'trace_id': '5e01127c0bb131c2'}}

I see that the key is present in util.py though

**Comment by iSarabjitDhiman** [comment]
> Might be related to the issue solved in your last commit
> 
> API Updated Successfully. Could not login account with auth_token, Twitter returned {'message': 'The following features cannot be null: creator_subscriptions_tweet_preview_api_enabled', 'extensions': {'name': 'BadRequestError', 'source': 'Client', 'code': 336, 'kind': 'Validation', 'tracing': {'trace_id': '5e01127c0bb131c2'}}, 'code': 336, 'kind': 'Validation', 'name': 'BadRequestError', 'source': 'Client', 'tracing': {'trace_id': '5e01127c0bb131c2'}}
> 
> I see that the key is present in util.py though

Yes, it was similar to the last commit, had to update request features to fix the issue. Twitter has been keep on making these changes lately, we have to keep up with the latest changes.

Keep me posted, if you notice any changes.

Thanks.
