### ISSUE TITLE
The following features cannot be null: verified_phone_label_enabled, responsive_web_graphql_timeline_navigation_enabled, responsive_web_media_download_video_enabled, responsive_web_graphql_exclude_directive_enabled, responsive_web_graphql_skip_user_profile_image_extensions_enabled

### ISSUE THREAD

**Issue by ihabpalamino** [iSarabjitDhiman/TweeterPy#24]
i am using async_await branch i got the his message ;"The following features cannot be null: verified_phone_label_enabled, responsive_web_graphql_timeline_navigation_enabled, responsive_web_media_download_video_enabled, responsive_web_graphql_exclude_directive_enabled, responsive_web_graphql_skip_user_profile_image_extensions_enabled" and return and empty list

**Comment by iSarabjitDhiman** [comment]
> i am using async_await branch i got the his message ;"The following features cannot be null: verified_phone_label_enabled, responsive_web_graphql_timeline_navigation_enabled, responsive_web_media_download_video_enabled, responsive_web_graphql_exclude_directive_enabled, responsive_web_graphql_skip_user_profile_image_extensions_enabled" and return and empty list
> 

Could u please tell what kind of data you are trying to fetch ? Or which TweeterPy method u r using?

**Comment by codilau** [comment]
@ihabpalamino, off-topic, but i suggest trying to synthetize the titles of the issues, it's unhelpful to paste the error code there. Thanks

**Comment by ihabpalamino** [comment]
it's working again i just needed to do update

**Comment by iSarabjitDhiman** [comment]
> it's working again i just needed to do update

Alright, thanks for the update. Closing the issue for now.
