### ISSUE TITLE
historical data

### ISSUE THREAD

**Issue by CharlesFr** [iSarabjitDhiman/TweeterPy#26]
I can see the following code returns the latest 100 tweets, it is possible to get more history?

```python
from tweeterpy import TweeterPy

twitter = TweeterPy()

user = twitter.get_user_id("elonmusk")

tweets = twitter.get_user_tweets(user)

print(tweets)
```

**Comment by iSarabjitDhiman** [comment]
Hey @CharlesFr 

Yes, you can fetch older tweets than just 100 latest ones. For that, you have to be logged in (try not to use your personal account). Twitter shows only a limited amount of data to the guest users. You can get as much as you want once you log in. 

But you are talking about data like 5-10years old (like in the Official [Twitter Historical API](https://developer.twitter.com/en/docs/tutorials/choosing-historical-api)), that might not be possible yet unless you have that many twitter accounts to make requests. By default the tweets are sorted by time so going back to 5-10 years old tweets may take a while and you may end up getting your account banned if using only one account for scraping.
