### ISSUE TITLE
Expecting value: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by codilau** [iSarabjitDhiman/TweeterPy#3]
Hi,
Giving this a spin i'm not getting any data in either **get_user_tweets**, **get_list_tweets**, **search**, **get_user_tweets**, **get_liked_tweets** or **get_user_timeline**.
I like the pickled session resuming, good ideea.
The **get_user_id** returns correctly
Traced it back to the make_request inside request_util that raises the exception in the title, after the retries.
The response dictionary is as follows:
**{'data': [], 'cursor_endpoint': None, 'has_next_page': True}**

for the get_user_timeline these are the urls that get hit:
https://twitter.com/i/api/graphql/Uv42IObcWFhsgKHYEh5Brw/HomeTimeline
https://twitter.com/i/api/graphql/Uv42IObcWFhsgKHYEh5Brw/HomeTimeline
https://twitter.com/i/api/graphql/Uv42IObcWFhsgKHYEh5Brw/HomeTimeline
Expecting value: line 1 column 2 (char 1)

EDIT:
Just saw the closed issue.
I can confirm i'm not using proxies and I can use other twitter libraries. Python3.10.11

**Comment by iSarabjitDhiman** [comment]
**Duplicate** : Check #2
