### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by TongJin123** [iSarabjitDhiman/TweeterPy#36]
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url

**Comment by iSarabjitDhiman** [comment]
> requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url

The api rate limit might have exhausted. Try again in something like an hour or two. If it still doesnt work, please drop the url here. You can grab it from the traceback or log file.
