### ISSUE TITLE
tweeterpy 1.0.10 requires charset-normalizer==3.1.0, but you have charset-normalizer 2.1.1 which is incompatible.

### ISSUE THREAD

**Issue by codilau** [iSarabjitDhiman/TweeterPy#42]
Is there any issue if using an older version of charset-normalizer? OpenAI for some reason wants version 2.1.1 and also the aiohttp 3.8.1 wants something lower than 3.0

**Comment by iSarabjitDhiman** [comment]
Feel free to use the latest version. There should not be any issue. I will update the dependencies to the latest version soon.
