### ISSUE TITLE
twitter.get_list_tweets gives an error

### ISSUE THREAD

**Issue by icematerial** [iSarabjitDhiman/TweeterPy#44]
twitter = TweeterPy()
twitter.load_session("login.pkl")
list_id = "xxxxxxxxxx"
twitter.get_list_tweets(list_id, end_cursor=None, total=50)
This code suddenly stopped working.

Has the List endpoint（= TWEETS_LIST_ENDPOINT） changed?

twitter.get_user_id('elonmusk')
twitter.get_user_media('elonmusk', end_cursor=None, total=2)
works fine.

thanks,

**Comment by iSarabjitDhiman** [comment]
Hey @icematerial 

I just tested it on my end, you are right. Twitter made changes to the feature switches, you might need to pass extra features to the params. Or you can wait for me to fix it. I m trying to come up with some permanent solution, so it might take some time.

**Comment by icematerial** [comment]
Thank you for your investigation.
I will wait for you to fix it.
Thank you for your kind assistance. I really appreciate it!
