### ISSUE TITLE
 [ERROR] :: 429 Client Error: Too Many Requests for url。 I get an error when I get too many tweets

### ISSUE THREAD

**Issue by baitu026** [iSarabjitDhiman/TweeterPy#47]
Is there any good solution?

**Comment by iSarabjitDhiman** [comment]
Apparently you ran out of api rate limits. I recommend you to keep an eye on the rate limits. Usually the rate limits gets renewed in every 15 minutes, but again it may vary in some cases, so please keep on checking these rate limits. You can check #29
You can also disable the pagination and handle the requests manually, check the [example code](https://github.com/iSarabjitDhiman/TweeterPy/blob/master/docs/docs.md#example---get-user-tweets-pagination-usage).
