### ISSUE TITLE
Task index - list index out of range

### ISSUE THREAD

**Issue by 4yR1l1k** [iSarabjitDhiman/TweeterPy#5]
**Python version:** 3.10

**Code:**
from tweeterpy import TweeterPy
from tweeterpy import config

def main():
    config.TIMEOUT = 5
    config.PROXY = {'http': 'xx.xxx.xx.xx', 'https': 'xx.xxx.xx.xx'}
    twitter = TweeterPy()
    print(twitter.get_user_id('elonmusk'))
    print(twitter.get_user_info('elonmusk'))
    # print(twitter.get_user_data('elonmusk'))
    # print(twitter.get_user_tweets('elonmusk', total=200))
    # print(twitter.get_user_media('elonmusk', total=100))

if __name__ == "__main__":
    main()

**Error:**
Traceback (most recent call last):
  File "/home/machine/Desktop/twscrape/id.py", line 17, in <module>
    main()
  File "/home/machine/Desktop/twscrape/id.py", line 9, in main
    print(twitter.get_user_id('elonmusk'))
  File "/usr/local/lib/python3.10/site-packages/tweeterpy/tweeterpy.py", line 110, in wrapper
    self.login()
  File "/usr/local/lib/python3.10/site-packages/tweeterpy/tweeterpy.py", line 189, in login
    TaskHandler().login(username, password)
  File "/usr/local/lib/python3.10/site-packages/tweeterpy/login_util.py", line 91, in login
    task_id = [task_id for task_id in task_flow_mapper.keys() if task_id in tasks][0]
IndexError: list index out of range

**Question:**

I've just found a proxy and trying your example code above. The twitter username and password are applied correctly. What am I doing wrong and getting this error?

**Comment by iSarabjitDhiman** [comment]
> **Python version:** 3.10
> 
> **Code:**
> from tweeterpy import TweeterPy
> from tweeterpy import config
> 
> def main():
>     config.TIMEOUT = 5
>     config.PROXY = {'http': 'xx.xxx.xx.xx', 'https': 'xx.xxx.xx.xx'}
>     twitter = TweeterPy()
>     print(twitter.get_user_id('elonmusk'))
>     print(twitter.get_user_info('elonmusk'))
>     # print(twitter.get_user_data('elonmusk'))
>     # print(twitter.get_user_tweets('elonmusk', total=200))
>     # print(twitter.get_user_media('elonmusk', total=100))
> 
> if __name__ == "__main__":
>     main()
> 
> 
> **Error:**
> Traceback (most recent call last):
>   File "/home/machine/Desktop/twscrape/id.py", line 17, in <module>
>     main()
>   File "/home/machine/Desktop/twscrape/id.py", line 9, in main
>     print(twitter.get_user_id('elonmusk'))
>   File "/usr/local/lib/python3.10/site-packages/tweeterpy/tweeterpy.py", line 110, in wrapper
>     self.login()
>   File "/usr/local/lib/python3.10/site-packages/tweeterpy/tweeterpy.py", line 189, in login
>     TaskHandler().login(username, password)
>   File "/usr/local/lib/python3.10/site-packages/tweeterpy/login_util.py", line 91, in login
>     task_id = [task_id for task_id in task_flow_mapper.keys() if task_id in tasks][0]
> IndexError: list index out of range
> 
> 
> **Question:**
> 
> I've just found a proxy and trying your example code above. The twitter username and password are applied correctly. What am I doing wrong and getting this error?

Have you tried it without the proxy ? If it's working without the proxy, then you have to use premium proxies i.e. residential proxies.

**Comment by iSarabjitDhiman** [comment]
> **Python version:** 3.10
> 
> **Code:** from tweeterpy import TweeterPy from tweeterpy import config
> 
> def main(): config.TIMEOUT = 5 config.PROXY = {'http': 'xx.xxx.xx.xx', 'https': 'xx.xxx.xx.xx'} twitter = TweeterPy() print(twitter.get_user_id('elonmusk')) print(twitter.get_user_info('elonmusk')) # print(twitter.get_user_data('elonmusk')) # print(twitter.get_user_tweets('elonmusk', total=200)) # print(twitter.get_user_media('elonmusk', total=100))
> 
> if **name** == "**main**": main()
> 
> **Error:** Traceback (most recent call last): File "/home/machine/Desktop/twscrape/id.py", line 17, in main() File "/home/machine/Desktop/twscrape/id.py", line 9, in main print(twitter.get_user_id('elonmusk')) File "/usr/local/lib/python3.10/site-packages/tweeterpy/tweeterpy.py", line 110, in wrapper self.login() File "/usr/local/lib/python3.10/site-packages/tweeterpy/tweeterpy.py", line 189, in login TaskHandler().login(username, password) File "/usr/local/lib/python3.10/site-packages/tweeterpy/login_util.py", line 91, in login task_id = [task_id for task_id in task_flow_mapper.keys() if task_id in tasks][0] IndexError: list index out of range
> 
> **Question:**
> 
> I've just found a proxy and trying your example code above. The twitter username and password are applied correctly. What am I doing wrong and getting this error?


Hey, I guess it was some issue with the login method. I just fixed it. Hopefully, it should be working fine now. Try it !!
