### ISSUE TITLE
get_user_tweets count has no effect

### ISSUE THREAD

**Issue by anxiaochuang** [iSarabjitDhiman/TweeterPy#55]
Hello, I found two problems, which are:
1. The data obtained by get_user_tweets is incomplete
2.get_user_tweets count does not take effect
Here is my code, take a look, is it the problem of the package or my code:
 tweets = await user.get_tweets('Tweets',10)
            for tweet in tweets:
                print(tweet.created_at)
                print(tweet.text)
thank you!

**Comment by iSarabjitDhiman** [comment]
Hey @anxiaochuang 
You have to specify 10 as a keyword argument, like this : total=10. Besides, async-await branch is no longer maintained. So I am not sure if its still working. Please read the docs carefully.
