### ISSUE TITLE
Cannot get full 'full_text'

### ISSUE THREAD

**Issue by zxj0302** [iSarabjitDhiman/TweeterPy#60]
When I was trying to scrape a tweet with tweet_id, I used get_retweet() function. However, the 'full_text' attribute in the returned structure is not complete. For example:

>id = 1623629869908213760
>result = twitter.get_tweet(id)

The tweet content extracted from 'full_text' in 'result' has some part missing in the end. Is there are some limitations for the text length? I also tried to 'log in', still cannot get 'full' text.

**Comment by iSarabjitDhiman** [comment]
Hmmm that's strange, I tried it on my end it works fine.
Maybe you are extracting the incorrect datapoint?
You can also use the Tweet dataclass to extract common datapoints.

```python
from tweeterpy.util import Tweet

id = 1623629869908213760
result = twitter.get_tweet(id)
tweet = Tweet(result)
print(tweet)

# you can also convert it into dictionary
print(tweet.dict())
```

Let me know if it works.

**Comment by zxj0302** [comment]
Thank you so much! It works! Maybe something went wrong in my code but now it works perfectly! Thank you again bro.
I will try to use Residential proxy to scrape tons of tweets for next step. Your work helps me a lot!!!

**Comment by iSarabjitDhiman** [comment]
You're welcome. Feel free to close the issue.

**Comment by zxj0302** [comment]
> You're welcome. Feel free to close the issue.

Thank you!
