### ISSUE TITLE
end_cursor value

### ISSUE THREAD

**Issue by nballen-tx** [iSarabjitDhiman/TweeterPy#7]
Hi,

In get_user_tweets fucntion, I see I can pass the end_cursor value to have it start from the a certain tweet.

I've tried to use the cursor_endpoint value from the function's returned data. but it doesn't work.

Something looks like this:
'cursor_endpoint': 'DAABCgABF1OKqJc__-gKAAIXRIgW-doQAAgAAwAAAAIAAA'

or I tried 
'entryId': 'tweet-1680771569491271681' or 1680771569491271681

None of these seems to work.

Can you please advise what value should I use?

Thanks,

**Comment by iSarabjitDhiman** [comment]
Hey, 
Its strange, I just tested it, its working just fine for me.
Here is how I used it :

```python
from tweeterpy import TweeterPy
twitter = TweeterPy()
# load or log into a session

# get initial data
tweets = twitter.get_user_tweets("elonmusk")

# then I Interrupted it with Ctrl + C and grabbed the cursor_endpoint from tweets['cursor_endpoint'] and used it in the next request.
cursor = tweets['cursor_endpoint']

# resume where you left off
more_tweets = twitter.get_user_tweets("elonmusk",end_cursor=cursor)

# you can test it with the endcursor I got
# below was the actual cursor for me
# data = twitter.get_user_tweets("elonmusk",end_cursor="DAABCgABF1OTTe4__80KAAIXS0buydYgAQgAAwAAAAIAAA")
``

>

**Comment by nballen-tx** [comment]
Thanks for taking a look.

Tried the same on my end.

twitter = TweeterPy()
twitter.load_session(session_file_path=session_path)

# get initial data
tweets = twitter.get_user_tweets("elonmusk",total=3)

# then I Interrupted it with Ctrl + C and grabbed the cursor_endpoint from tweets['cursor_endpoint'] and used it in the next request.
cursor = tweets['cursor_endpoint']

# resume where you left off
more_tweets = twitter.get_user_tweets("elonmusk",end_cursor=cursor,total=3)

The "tweets" are fine as they are the top 3 tweets, but "more_tweet" are a bit problematic as it returned some old 2009 tweets. instead of #4-6 tweets.

Thanks,

**Comment by iSarabjitDhiman** [comment]
Hey @nballen-tx 
I understand what you saying, the reason why there are some old tweets in there :

- The user has retweeted an old tweet.
- There are profile conversations included in the dataset
- Promotional tweets are included too.

Twitter by default includes these profile conversations and promotional tweets.

This is what I usually do to deal with it :

If you take a look at your data, you will notice that each item has a "entryId" which either starts with "tweet-(some_unique_id)", "profile-conversation-(some_unique_id)" or "promoted-(some_unique_id)". 

So I just iterate through the whole dataset and filter them by entryId, the one starts with "tweet-".

```python
data = [item for item in tweets["data"] if item.get("entryId",None) and item["entryId"].startswith("tweet")]
```

**Comment by nballen-tx** [comment]
Thanks for the explanation!
