### ISSUE TITLE
Failure to login in

### ISSUE THREAD

**Issue by BillChan226** [iSarabjitDhiman/TweeterPy#73]
Thanks for the incredible work! Whenever I type in my user name and password and try to login it using `twitter.login()`, it always gives me the error `Exception: Couldn't find the following Task Ids []`. Could you please help me with that?

**Comment by iSarabjitDhiman** [comment]
> Thanks for the incredible work! Whenever I type in my user name and password and try to login it using `twitter.login()`, it always gives me the error `Exception: Couldn't find the following Task Ids []`. Could you please help me with that?

Hey @BillChan226 
Twitter recently implemented this X-Client-Transaction-Id validation thing, I have been working on this one for a week now. I have already solved it, I just need to do some code refactoring and then I will push the changes, maybe later today.

**Comment by BillChan226** [comment]
Thank you very much! This is very helpful:)

**Comment by BillChan226** [comment]
Hi Sarabjit,

Thank you for the great efforts! I'm wondering if could kindly update the code today with the new login proxy? Thank you!!

**Comment by iSarabjitDhiman** [comment]
Hey @BillChan226 
I will try to push today. I have been kind of busy with my other projects, but I will try.
You can log in with the auth token in the meantime.
Otherwise, you can check my profile, I have already created a [new repo](https://github.com/iSarabjitDhiman/XClientTransaction) with the solution. You just have to integrate the repo into TweeterPy and it would work.
All you have to do is attach an additional header X-Client-Transaction-Id while making log in requests in the login_util.py module.

**Comment by BillChan226** [comment]
Thank you! I'm using auth token to login and it's working nice and clean now! Thank you!

**Comment by nepaul** [comment]
Hi @iSarabjitDhiman, when will you be able to push your latest fixes? I have encountered a similar issue.

**Comment by iSarabjitDhiman** [comment]
> Hi @iSarabjitDhiman, when will you be able to push your latest fixes? I have encountered a similar issue.

Hey @nepaul
I will push the changes later today.

**Comment by zekhoi** [comment]
Does adding that generator fix it? It doesn't seem to work for me.

**Comment by iSarabjitDhiman** [comment]
> Does adding that generator fix it? It doesn't seem to work for me.

Yes it does. What error does it show in your case? Could you please show me the error you are getting? I will take a look.

**Comment by zekhoi** [comment]
nvm, it works
