### ISSUE TITLE
Unable to login 2FA with TOTP code accounts

### ISSUE THREAD

**Issue by codilau** [iSarabjitDhiman/TweeterPy#75]
Hi,
Congrats on the outstanding recent improvements in the login of the accounts.
I noticed the accounts with 2FA are not supported.
Are there any plans to support this type of account?
Thanks

`Exception: 
Couldn't find the following Task Ids:
['LoginTwoFactorAuthChallenge', 'LoginTwoFactorAuthChooseMethod', 'login_security_key_not_supported_cta']`

**Comment by iSarabjitDhiman** [comment]
> Hi,
> Congrats on the outstanding recent improvements in the login of the accounts.
> I noticed the accounts with 2FA are not supported.
> Are there any plans to support this type of account?
> Thanks
> 
> `Exception: 
> Couldn't find the following Task Ids:
> ['LoginTwoFactorAuthChallenge', 'LoginTwoFactorAuthChooseMethod', 'login_security_key_not_supported_cta']`

I will implement this feature this weekend.

**Comment by iSarabjitDhiman** [comment]
✅ Added in [85bbc31](https://github.com/iSarabjitDhiman/TweeterPy/commit/85bbc31a396284ef11228e7a49a906aef0037809)
