### ISSUE TITLE
Support for endpoint https://x.com/i/api/1.1/users/email_phone_info.json?include_pending_email=true'

### ISSUE THREAD

**Issue by burruplambert** [iSarabjitDhiman/TweeterPy#76]
Is it possible to add support for this api v1.1 endpoint?

**Comment by iSarabjitDhiman** [comment]
Yes it is, but it will only work for the authenticated users. I mean we cannot get someone's contact info with this endpoint, can we?

**Comment by burruplambert** [comment]
No, it is only for the logged in user. Brilliant work btw on your login flow. The best library I have seen to handle the flow. The only subtask_id I think not accounted for is ArkoseLogin.

**Comment by iSarabjitDhiman** [comment]
> No, it is only for the logged in user. Brilliant work btw on your login flow. The best library I have seen to handle the flow. The only subtask_id I think not accounted for is ArkoseLogin.

I haven't got ArkoseLogin so far, how do I get it? Do I have to sign in from a new IP address?

**Comment by burruplambert** [comment]
> > No, it is only for the logged in user. Brilliant work btw on your login flow. The best library I have seen to handle the flow. The only subtask_id I think not accounted for is ArkoseLogin.
> 
> I haven't got ArkoseLogin so far, how do I get it? Do I have to sign in from a new IP address?

I'm not exactly sure on how to force trigger it. Probably multiple failed login attempts. Or multiple successful logins repeatedly from the same IP etc. I think I have an account that asks for Arkose somewhere. I can share the details of the account privately if you like.

**Comment by iSarabjitDhiman** [comment]
> > > No, it is only for the logged in user. Brilliant work btw on your login flow. The best library I have seen to handle the flow. The only subtask_id I think not accounted for is ArkoseLogin.
> > 
> > I haven't got ArkoseLogin so far, how do I get it? Do I have to sign in from a new IP address?
> 
> I'm not exactly sure on how to force trigger it. Probably multiple failed login attempts. Or multiple successful logins repeatedly from the same IP etc. I think I have an account that asks for Arkose somewhere. I can share the details of the account privately if you like.

That would be great if you could share.
You can change the password later. You can either share here, send me a message on my social media or email me.
