### ISSUE TITLE
{'code': 88, 'message': 'Rate limit exceeded.'} is not handled

### ISSUE THREAD

**Issue by burruplambert** [iSarabjitDhiman/TweeterPy#80]
This is what is currently returned. No further information is provided.

```
2024-09-05 10:56:20,013 [ERROR] :: Couldn't find guest token
2024-09-05 10:56:20,013 [ERROR] :: Couldn't find guest token
2024-09-05 10:56:20,014 [ERROR] :: Couldn't generate a new session.
```

However the actual reason was because of a rate limit. The response was

`{'code': 88, 'message': 'Rate limit exceeded.'}`

It is not currently handed in util.check_for_errors() or util.check_api_rate_limits()

**Comment by iSarabjitDhiman** [comment]
Hey @burruplambert,

Which line or url does return the given rate limit exceeded response?
