### ISSUE TITLE
Tweet URL

### ISSUE THREAD

**Issue by rehan243** [iSarabjitDhiman/TweeterPy#9]
Hey, 
Can you help me how can I get a tweet URL by using TweeterPy?

**Comment by iSarabjitDhiman** [comment]
Duplicate : #13 

Here is how you can [get tweet URL](https://github.com/iSarabjitDhiman/TweeterPy/issues/13#issuecomment-1656022050)s if you are using async-await branch.

But if you are using the master branch use [this block of code](https://github.com/iSarabjitDhiman/TweeterPy/issues/13#issuecomment-1652135672)
